import { describe, it, expect } from 'vitest'
import { generateReceiptPdf } from '@/lib/generateReceiptPdf'
import type { ReceiptData } from '@/lib/receiptData'

const sampleReceiptData: ReceiptData = {
  payerAddress: '0x1234567890abcdef1234567890abcdef12345678',
  recipientAddress: '0xabcdefabcdefabcdefabcdefabcdefabcdefabcd',
  tokenSymbol: 'USDC',
  tokenName: 'USD Coin',
  amount: '100.00',
  chainName: 'Base',
  chainId: 8453,
  txHash: '0x' + 'a'.repeat(64),
  blockExplorerUrl: 'https://basescan.org',
  memo: 'Test payment',
  confirmedAt: 1700000000000,
  feeTotal: '100000000',
  feeAmount: '1000000',
  feeNet: '99000000',
  feeRateBps: '100',
  tokenDecimals: 6,
}

describe('generateReceiptPdf unit tests', () => {
  it('PDF title is "Transfer Receipt" for English locale', async () => {
    const doc = await generateReceiptPdf(sampleReceiptData, 'en')
    const pdfRaw = doc.output()
    expect(pdfRaw).toContain('Transfer Receipt')
  })

  it('PDF title uses Thai locale text (not English) when locale is "th"', async () => {
    const doc = await generateReceiptPdf(sampleReceiptData, 'th')
    const pdfRaw = doc.output()
    // jsPDF may encode Thai characters, so verify the English title is NOT present
    expect(pdfRaw).not.toContain('Transfer Receipt')
  })

  it('PDF contains footer "Generated by Payo" for English locale', async () => {
    const doc = await generateReceiptPdf(sampleReceiptData, 'en')
    const pdfRaw = doc.output()
    expect(pdfRaw).toContain('Generated by Payo')
  })

  it('PDF uses A4 page size (210mm x 297mm)', async () => {
    const doc = await generateReceiptPdf(sampleReceiptData, 'en')
    const width = doc.internal.pageSize.getWidth()
    const height = doc.internal.pageSize.getHeight()
    expect(width).toBeCloseTo(210, 0)
    expect(height).toBeCloseTo(297, 0)
  })

  it('PDF contains "Payo" in header', async () => {
    const doc = await generateReceiptPdf(sampleReceiptData, 'en')
    const pdfRaw = doc.output()
    expect(pdfRaw).toContain('Payo')
  })
})
